---
deployment:
  tasks:
    - export DEPLOYPATH=/home/weddingkat/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp blue-heart-svgrepo-com.svg $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
